#!/usr/bin/env bash
# Audits DNS A records for specified subdomains of a domain

dns_info() {
	domain=$1
	subdomain=$2
	dig_output=$(dig "$subdomain.$domain" +short)
	record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ { getline; print $4 }')
	echo "The subdomain $subdomain is a $record_type record and points to $dig_output"
}

main() {
	domain=$1
	subdomain=$2

	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
		for sub in "${subdomains[@]}"; do
			dns_info "$domain" "$sub"
		done
	else
		dns_info "$domain" "$subdomain"
	fi
}

main "$1" "$2"
