#!/usr/bin/env bash
# Installs Nginx

apt-get update
apt install -y nginx
echo "Hello World!" | tee /var/www/html/index.html

echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.linkedin.com/in/ikechukwu-nweke-18b15118b;
    }
}" > /etc/nginx/sites-available/default
service nginx start
