#!/usr/bin/env bash
# Pings an IP address passed as an argument to it
# The IP is ping-ed 5 times

if [ $# -ne 1 ];
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

IP_ADD="$1"
ping -c 5 "$IP_ADD"
