#!/usr/bin/env bash
# Configures Nginx to listen on port 80

DESIRED_PORT=80
CONF="/etc/nginx/sites-enabled/default"

sed -i "s/listen [0-9]\+/listen $desired_port/" "$nginx_conf"
service nginx restart
