#!/usr/bin/env bash
# Creates a file '/var/run/myscript.pid' that contains its PID
# Displays "To infinity and beyond" indefinitely and displays
#+ a couple of messages when SIGTERM, SIGINT and SIGQUIT are
#+ are passed.

delete_file() {
	rm /var/run/myscript.pid
	exit
}

echo > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && delete_file' SIGTERM
	trap 'delete_file' SIGQUIT
done
