#!/usr/bin/env bash
# Displays from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Fizz when a multiple of 3
# Buzz when number is a multiple of 5

for n in {1..100}
do
	if (( n % 3 == 0 && n % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( n % 5 == 0 ))
	then
		echo "Buzz"
	elif (( n % 3 == 0 ))
	then
		echo "Fizz"
	else
		echo "$n"
	fi
done
